Mission11_Nance/Components/BookTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission11_Nance.Models;

namespace Mission11_Nance.Components
{
    public class BookTypesViewComponent : ViewComponent
    {
        private IBookRepository _bookRepo;

        //Constructor

        public BookTypesViewComponent(IBookRepository temp) 
        {
            _bookRepo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedBookType = RouteData?.Values["bookType"];
            var bookTypes = _bookRepo.Books
                .Select(x => x.Classification)
                .Distinct()
                .OrderBy(x => x);
            return View(bookTypes);
        }
    }
}

Mission11_Nance/Views/Shared/BookSummary.cshtml
@using Mission11_Nance.Infrastructure
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Book

<div class="card m-1 p-1">
    <h4>
        @Model.Title
        <span class="badge rounded-pill bg-primary text-white float-end"><small>Author: @Model.Author</small></span>
    </h4>
    <ul>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Page Count: @Model.PageCount</li>
        <li>Price: $@Model.Price</li>

    </ul>

    <form id=@Model.BookId method="post" asp-page="/Cart">
        <input type="hidden" asp-for="BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <button type="submit" class="btn-outline-success btn-sm float-end">Add to Cart</button>
    </form>
    
</div>

Mission11_Nance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission11_Nance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mission11_Nance.styles.css" asp-append-version="true" />
</head>
<body>

    <!--Add navbar with dynamic page widths-->

    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">LIBRARY</span>
        <a asp-page="/Predict" class="btn btn-primary m-lg-2">Predictions</a>
    </div>
    <div class="row m-1 p-1">
        <div class="col-3">
            <vc:book-types />
        </div>
        <div class="container col-9">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>